version: '3.8'
services:
  assessment:
    image: mrksdh/assessment
    container_name: assessment
    ports:
      - "8080:8080"
    networks:
      - my_networks

 # builds a Java application container that relies on another service and shares the host's network.
  java-app:
    build: .
    container_name: java
    depends_on:
      - assessment
    network_mode: host

  # Define networks for the services
networks:
  my_networks:
    driver: bridge